name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Set up Node in a clean workspace (no package.json yet)
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # 2) Activate Corepack and pin Yarn 4.9.4 globally for this job
      - name: Enable Corepack & activate Yarn 4.9.4
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate
          yarn -v

      # 3) Now checkout the repo (Yarn 4 is active already)
      - uses: actions/checkout@v4

      # 4) Install / build / upload
      - name: Install deps (immutable)
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
